# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64

name: vault
channels:
  - default
  - conda-forge
  - fastai
  - plotly
dependencies:
  - python=3.7
  - ipython=7.1.1
  - notebook
  - pandas>=1.2.0
  - skyfield
  - plotly
  - python-kaleido
  - astropy
  - sgp4
  # dev
  - flask
  - nbdev>=1.1.11
  - nbconvert>=5.6.1
  - ipywidgets
  - pyarrow
  - pip>=19.3.1
  - pip:
    

#dev_requirements = nbdev>=1.0.10 ipywidgets flask scikit-image pyarrow


