channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7
    - ipython=7.1.1
    - prompt_toolkit==2.0.10
    - notebook
    - numpy
    - pandas
    - scikit-learn
    - pip>=19.3.1
    - pip:
        - geopy
        - plotly==4.14.1
        - hdbscan