name: vaultgeowextras
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7
  - ipython=7.1.1
  - notebook
  - requests
  - pip>=19.3.1
  - pip:
    - ephem
    - pyorbital
    - skyfield
    - astropy
    - sgp4